health status ajouté avec boucle

diff --git a/.github/workflows/build@test.yml b/.github/workflows/build@test.yml
--- a/.github/workflows/build@test.yml
+++ b/.github/workflows/build@test.yml
@@ -38,11 +38,36 @@ jobs :
             files : ./Dockerfile
             only-severity : critical,high
             exit-code : false
-  
-# jobs :
-#   build_test :
-#     runs-on : ubuntu-latest
-#     steps :
-#         - name : Checkout code
-        
-        
+
+  check_containers:
+    runs-on: ubuntu-latest
+    needs: build_test
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Launch docker-compose
+        run: docker compose up -d
+        env:
+          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
+          MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
+          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
+
+      - name: Check containers health status
+        run: |
+          TIMEOUT=180
+          ELAPSED=0
+          SERVICES="db_mysql db_mongo admin_mysql admin_mongo api"
+
+          echo "Waiting for containers to be healthy..."
+          sleep $TIMEOUT
+          docker compose ps
+
+          for SERVICE in $SERVICES; do
+            STATUS=$(docker inspect $(docker compose ps -q $SERVICE) --format='{{.State.Health.Status}}')
+            echo "$SERVICE: $STATUS"
+            [ "$STATUS" != "healthy" ] && echo "ERROR: $SERVICE is not healthy" && exit 1
+          done
+          echo "All containers are healthy!"
+
